### ISSUE TITLE
Tests don't run out of the box due to missing /etc/aclhound/aclhound.conf

### ISSUE THREAD

**Issue by jzohrab** [job/aclhound#53]
Setting up ACLHound locally following the [config documentation](https://github.com/job/aclhound/blob/master/INSTALL-CONFIG.md) - some deviations from the instructions actually, but should be ok:

```
$ git clone git@github.com:job/aclhound.git
$ cd aclhound
$ virtualenv venv
$ source venv/bin/activate
$ pip install -r requirements.txt
$ make test
```
snip some outputs, and get failures:

```
======================================================================
ERROR: test_01__build_ios (tests.test_regression.TestAclhound)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jzohrab/Documents/Projects/aclhound/tests/test_regression.py", line 68, in test_01__build_ios
    u'debug': False, u'jenkins': True})
  File "/Users/jzohrab/Documents/Projects/aclhound/aclhound/cli.py", line 215, in __init__
    self._settings = Settings()
  File "/Users/jzohrab/Documents/Projects/aclhound/aclhound/cli.py", line 82, in __init__
    sys.exit(2)
SystemExit: 2

======================================================================
ERROR: test_02__build_asa (tests.test_regression.TestAclhound)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jzohrab/Documents/Projects/aclhound/tests/test_regression.py", line 87, in test_02__build_asa
    u'debug': False, u'jenkins': True})
  File "/Users/jzohrab/Documents/Projects/aclhound/aclhound/cli.py", line 215, in __init__
    self._settings = Settings()
  File "/Users/jzohrab/Documents/Projects/aclhound/aclhound/cli.py", line 82, in __init__
    sys.exit(2)
SystemExit: 2
```

The failure is due to cli.py's lines:

```
        if not os.path.exists('/etc/aclhound/aclhound.conf'):
            print("ERROR: Could not open /etc/aclhound/aclhound.conf")
            print("Has ACLHound been properly installed? Contact your admin")
            sys.exit(2)
```

The fresh install creates aclhound.conf.dist, but not aclhound.conf.

If you give some notes on how this should be resolved here, I can fork and PR back to master.  Should I just copy the .dist file to .conf?

**Comment by jzohrab** [comment]
Have copied .dist file to .conf, running into further errors.  Will add comments to this issue as I run into them and resolve them.  Ideally, the tests would run successfully on initial check out.

**Comment by job** [comment]
A PR is most welcome when you have resolved the issues. While the project is mostly OS agnostic, I'd prefer to at least properly support Debian in a documented way. Thank you

**Comment by jzohrab** [comment]
Np, may need some guidance/feedback on my submission, and I'll make whatever adjustments needed.  Happy to contribute, thanks @job.

**Comment by jzohrab** [comment]
When PR #55 is closed, this issue can be closed.
